### ISSUE TITLE
[FR] Hide source file in multiple output files

### ISSUE THREAD

**Issue by rockandska** [DimitarPetrov/stegify#3]
Hi,

Will be really nice to be able to hide the source file in multiples files and take in account the order specified for the encode / decode steps.
It will prevent the ability to decode the source file if an image is missing or if the order is not correct.

Additionally, adding a password protection will be neat too

Regards,

**Comment by DimitarPetrov** [comment]
Hi @rockandska, i am glad you are interested in stegify! 👍

I have thought about this too, it would be nice for sure. 
However I am a little busy right now, but when have more free time definitely would figure that out!

Thanks and Regards,
Dimitar

**Comment by DimitarPetrov** [comment]
Hi @rockandska,
I am closing the issue as the implementation is provided.

Thank you again for your contribution.

Regards,
Dimitar
